name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_REPO: 'https://github.com/Siddhi1708/kubernetes-qst.git'
  BACKEND_IMAGE: 'siddhi178/backend:n70'
  FRONTEND_IMAGE: 'siddhi178/frontend:n70'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Backend image
        run: |
          docker build -t $BACKEND_IMAGE .
          docker push $BACKEND_IMAGE

      - name: Build and push Frontend image
        working-directory: qfrontend
        run: |
          docker build -t $FRONTEND_IMAGE .
          docker push $FRONTEND_IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set Kubeconfig context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        working-directory: k8s
        run: |
          kubectl apply -f frontend-deployment.yml
          kubectl apply -f backend-deployment.yml
          kubectl apply -f mysql-deployment.yml
