name: Deploy QST

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: actions/kubectl@v3
      
      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy Frontend
        run: kubectl apply -f k8s/frontend-deployment.yml

      - name: Deploy Backend
        run: kubectl apply -f k8s/backend-deployment.yml

      - name: Deploy Database
        run: kubectl apply -f k8s/mysql-deployment.yml
